// THIS FILE IS AUTOGENERATED. DO NOT EDIT
/* eslint-disable */
/* tslint:disable */
import * as body from './body'
export { body }
import * as inventory from './inventory'
export { inventory }
import * as items from './items'
export { items }
import * as locations from './locations'
export { locations }
export * from './LudumDare45Page'
export * from './monsters'
export * from './PanelStats'
export * from './skills'
import * as sosLd45 from './sosLd45'
export { sosLd45 }
export * from './TabBody'
export * from './TabFight'
export * from './TabInventory'
export * from './TabLocation'
export * from './Tabs'
export * from './TabScavenge'
export * from './TabSkills'